version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: room_booking_db
    restart: always
    environment:
      POSTGRES_USER: rb
      POSTGRES_PASSWORD: rb
      POSTGRES_DB: room_booking
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: